CREATE TABLE [dataload].[ArmyBudget] (
    [Id]                     INT            IDENTITY (1, 1) NOT NULL,
    [POSITION]               NVARCHAR (255) NULL,
    [FY]                     SMALLINT       NULL,
    [AMOUNT]                 NUMERIC (18)   NULL,
    [BO]                     NVARCHAR (1)   NULL,
    [BO_DESC]                NVARCHAR (255) NULL,
    [APPN]                   NVARCHAR (5)   NULL,
    [APPN_DESC]              NVARCHAR (255) NULL,
    [TC]                     NVARCHAR (50)  NULL,
    [APPN_CAT_ABBR]          NVARCHAR (255) NULL,
    [APPN_CAT_DESC]          NVARCHAR (255) NULL,
    [COMPO]                  NVARCHAR (255) NULL,
    [RC]                     NVARCHAR (5)   NULL,
    [RC_DESC]                NVARCHAR (255) NULL,
    [RC_TYPE]                NVARCHAR (255) NULL,
    [APE]                    NVARCHAR (10)  NULL,
    [APE_PT_DESC]            NVARCHAR (255) NULL,
    [AMSCO]                  NVARCHAR (255) NULL,
    [SAG]                    NVARCHAR (255) NULL,
    [SAG_DESC]               NVARCHAR (255) NULL,
    [BA]                     NVARCHAR (50)  NULL,
    [BA_DESC]                NVARCHAR (255) NULL,
    [SPC]                    NVARCHAR (50)  NULL,
    [ROLL_SSN]               NVARCHAR (255) NULL,
    [ROLL_SSN_DESC]          NVARCHAR (255) NULL,
    [MDEP]                   NVARCHAR (255) NULL,
    [MDEP_DESC]              NVARCHAR (255) NULL,
    [PEG]                    NVARCHAR (255) NULL,
    [PEG_DESC]               NVARCHAR (255) NULL,
    [ROC]                    NVARCHAR (4)   NULL,
    [ROC_DESC]               NVARCHAR (255) NULL,
    [CMD]                    NVARCHAR (2)   NULL,
    [CMD_DESC]               NVARCHAR (255) NULL,
    [CTYPE]                  NVARCHAR (255) NULL,
    [CTYPE_DESC]             NVARCHAR (255) NULL,
    [FSC]                    NVARCHAR (255) NULL,
    [FSC_DESC]               NVARCHAR (255) NULL,
    [UIC]                    NVARCHAR (6)   NULL,
    [UIC_DESC]               NVARCHAR (255) NULL,
    [DP99_DESC]              NVARCHAR (255) NULL,
    [DP99]                   NVARCHAR (255) NULL,
    [REIMC]                  NVARCHAR (255) NULL,
    [REIMS]                  NVARCHAR (255) NULL,
    [OSDPE]                  NVARCHAR (255) NULL,
    [OSDPE_DESC]             NVARCHAR (255) NULL,
    [OSDSEQNO]               NVARCHAR (255) NULL,
    [RIC]                    NVARCHAR (5)   NULL,
    [RIC_DESC]               NVARCHAR (255) NULL,
    [PID]                    NVARCHAR (50)  NULL,
    [PID_DESC]               NVARCHAR (255) NULL,
    [JCA_PORTFOLIO]          NVARCHAR (255) NULL,
    [MHC]                    NVARCHAR (50)  NULL,
    [MHC_DESC]               NVARCHAR (255) NULL,
    [FIC]                    NVARCHAR (255) NULL,
    [FIC_DESC]               NVARCHAR (255) NULL,
    [OBJECTIVE_ID]           NCHAR (1)      NULL,
    [OBJECTIVE]              NVARCHAR (255) NULL,
    [SUBOBJECTIVE_ID]        NVARCHAR (5)   NULL,
    [SUBOBJECTIVE]           NVARCHAR (255) NULL,
    [TASK_ID]                NVARCHAR (255) NULL,
    [TASK]                   NVARCHAR (255) NULL,
    [II_BIN]                 NVARCHAR (255) NULL,
    [EE_ROOT]                NVARCHAR (255) NULL,
    [EE_BOS]                 NVARCHAR (255) NULL,
    [TT_GROUP]               NVARCHAR (255) NULL,
    [SS_PROGRAM]             NVARCHAR (255) NULL,
    [DOLLAR_TYPE]            NVARCHAR (255) NULL,
    [DOLLAR_TYPE_DESC]       NVARCHAR (255) NULL,
    [APE6]                   NVARCHAR (255) NULL,
    [APE_DESC]               NVARCHAR (255) NULL,
    [APE_PT]                 NVARCHAR (255) NULL,
    [BSA]                    NVARCHAR (255) NULL,
    [CTC]                    NVARCHAR (255) NULL,
    [CWOC]                   NVARCHAR (255) NULL,
    [CYCLE_CODE]             NVARCHAR (255) NULL,
    [DMC]                    NVARCHAR (255) NULL,
    [MEMO]                   NVARCHAR (255) NULL,
    [MOR]                    NVARCHAR (255) NULL,
    [MOR_DESC]               NVARCHAR (255) NULL,
    [OMA_BIN]                NVARCHAR (255) NULL,
    [ORG]                    NVARCHAR (255) NULL,
    [OSDPE_PID]              NVARCHAR (255) NULL,
    [OSDPE_PID_DESC]         NVARCHAR (255) NULL,
    [POSITION_PUB_DATE]      NVARCHAR (255) NULL,
    [RAG]                    NVARCHAR (255) NULL,
    [TAC]                    NVARCHAR (255) NULL,
    [DATE_EFF]               DATE           NULL,
    [AmcosVersionId]         INT            NULL,
    [osd_location]           VARCHAR (75)   NULL,
    [osd_location_desc]      VARCHAR (75)   NULL,
    [facility_category]      VARCHAR (75)   NULL,
    [facility_category_desc] VARCHAR (75)   NULL,
    [osd_state_country]      VARCHAR (75)   NULL,
    [osd_state_country_desc] VARCHAR (75)   NULL,
    [installation_name]      VARCHAR (75)   NULL,
    [BLI]                    NVARCHAR (50)  NULL,
    [SUBTASK]                NVARCHAR (255) NULL,
    [SUBTASK_ID]             NVARCHAR (50)  NULL,
    [OSDPE_PID_GROUP]        NVARCHAR (50)  NULL,
    [OSD_PID_GROUP_DESC]     NVARCHAR (255) NULL,
    [OSD_PID_GROUP]          NVARCHAR (255) NULL,
    CONSTRAINT [PK_ArmyBudget] PRIMARY KEY CLUSTERED ([Id] ASC)
);











