CREATE TABLE [dataload].[MilitaryOverseasHousingAllowance] (
    [LOCCODE]                      NVARCHAR (50)  NOT NULL,
    [LOCNAME]                      NVARCHAR (100) NOT NULL,
    [Exchdate]                     INT            NOT NULL,
    [OHAEFDAT]                     INT            NOT NULL,
    [KEYLOC]                       NVARCHAR (50)  NOT NULL,
    [XRAT]                         FLOAT (53)     NOT NULL,
    [OCOLA_Index]                  INT            NOT NULL,
    [OCOLA_GroupCode]              INT            NOT NULL,
    [CLIM]                         INT            NOT NULL,
    [Perc_O_Utility_wDep]          INT            NOT NULL,
    [Perc_E_Utility_wDep]          INT            NOT NULL,
    [O_Utility_wDep]               INT            NOT NULL,
    [E_Utility_wDep]               INT            NOT NULL,
    [Perc_O_RentalAllowance_woDep] INT            NOT NULL,
    [Perc_E_RentalAllowance_woDep] INT            NOT NULL,
    [COLEFDAT]                     INT            NOT NULL,
    [O_MIHA]                       INT            NOT NULL,
    [E_MIHA]                       INT            NOT NULL,
    [auth_MIHA_security]           INT            NOT NULL,
    [Country_Code]                 NVARCHAR (50)  NOT NULL,
    [Currency_Code]                NVARCHAR (50)  NOT NULL,
    [Off_curr_name]                NVARCHAR (50)  NOT NULL,
    [Mkt_Curr]                     NVARCHAR (50)  NOT NULL,
    [Mkt_Name]                     NVARCHAR (50)  NOT NULL,
    [Grade]                        NVARCHAR (3)   NOT NULL,
    [GradeLevel]                   TINYINT        NOT NULL,
    [RentalAmt_wDep]               INT            NOT NULL,
    [AmcosVersionId]               INT            NOT NULL,
    CONSTRAINT [PK_MilitaryOverseasHousingAllowance] PRIMARY KEY CLUSTERED ([LOCCODE] ASC, [Grade] ASC, [GradeLevel] ASC, [AmcosVersionId] ASC)
);

