CREATE TABLE [DMDC].[BasePopulation] (
    [PayPlan]          NVARCHAR (3) NOT NULL,
    [CMF]              NVARCHAR (3) NOT NULL,
    [GradeType]        NVARCHAR (3) NOT NULL,
    [GradeLevel]       TINYINT      NOT NULL,
    [AccessionQuality] TINYINT      NOT NULL,
    [YOS0]             NUMERIC (7)  NULL,
    [YOS1]             NUMERIC (7)  NULL,
    [YOS2]             NUMERIC (7)  NULL,
    [YOS3]             NUMERIC (7)  NULL,
    [YOS4]             NUMERIC (7)  NULL,
    [YOS5]             NUMERIC (7)  NULL,
    [YOS6]             NUMERIC (7)  NULL,
    [YOS7]             NUMERIC (7)  NULL,
    [YOS8]             NUMERIC (7)  NULL,
    [YOS9]             NUMERIC (7)  NULL,
    [YOS10]            NUMERIC (7)  NULL,
    [YOS11]            NUMERIC (7)  NULL,
    [YOS12]            NUMERIC (7)  NULL,
    [YOS13]            NUMERIC (7)  NULL,
    [YOS14]            NUMERIC (7)  NULL,
    [YOS15]            NUMERIC (7)  NULL,
    [YOS16]            NUMERIC (7)  NULL,
    [YOS17]            NUMERIC (7)  NULL,
    [YOS18]            NUMERIC (7)  NULL,
    [YOS19]            NUMERIC (7)  NULL,
    [YOS20]            NUMERIC (7)  NULL,
    [YOS21]            NUMERIC (7)  NULL,
    [YOS22]            NUMERIC (7)  NULL,
    [YOS23]            NUMERIC (7)  NULL,
    [YOS24]            NUMERIC (7)  NULL,
    [YOS25]            NUMERIC (7)  NULL,
    [YOS26]            NUMERIC (7)  NULL,
    [YOS27]            NUMERIC (7)  NULL,
    [YOS28]            NUMERIC (7)  NULL,
    [YOS29]            NUMERIC (7)  NULL,
    [YOS30]            NUMERIC (7)  NULL,
    [YOS31]            NUMERIC (7)  NULL,
    [YOS32]            NUMERIC (7)  NULL,
    [YOS33]            NUMERIC (7)  NULL,
    [YOS34]            NUMERIC (7)  NULL,
    [YOS35]            NUMERIC (7)  NULL,
    [YOS36]            NUMERIC (7)  NULL,
    [YOS37]            NUMERIC (7)  NULL,
    [YOS38]            NUMERIC (7)  NULL,
    [YOS39]            NUMERIC (7)  NULL,
    [YOS40]            NUMERIC (7)  NULL,
    [YOSGreaterThan40] NUMERIC (7)  NULL,
    [YOSUnknown]       NUMERIC (7)  NULL,
    [YOSTotal]         NUMERIC (7)  NULL,
    CONSTRAINT [PK_BasePopulation] PRIMARY KEY CLUSTERED ([PayPlan] ASC, [CMF] ASC, [GradeType] ASC, [GradeLevel] ASC, [AccessionQuality] ASC)
);

