CREATE TABLE [DMDC].[ContinuationRates_Promoted] (
    [PayPlan]          NVARCHAR (3)   NOT NULL,
    [CMF]              NVARCHAR (3)   NOT NULL,
    [GradeType]        NVARCHAR (3)   NOT NULL,
    [GradeLevel]       TINYINT        NOT NULL,
    [AccessionQuality] TINYINT        NOT NULL,
    [YOS0]             NUMERIC (6, 2) NULL,
    [YOS1]             NUMERIC (6, 2) NULL,
    [YOS2]             NUMERIC (6, 2) NULL,
    [YOS3]             NUMERIC (6, 2) NULL,
    [YOS4]             NUMERIC (6, 2) NULL,
    [YOS5]             NUMERIC (6, 2) NULL,
    [YOS6]             NUMERIC (6, 2) NULL,
    [YOS7]             NUMERIC (6, 2) NULL,
    [YOS8]             NUMERIC (6, 2) NULL,
    [YOS9]             NUMERIC (6, 2) NULL,
    [YOS10]            NUMERIC (6, 2) NULL,
    [YOS11]            NUMERIC (6, 2) NULL,
    [YOS12]            NUMERIC (6, 2) NULL,
    [YOS13]            NUMERIC (6, 2) NULL,
    [YOS14]            NUMERIC (6, 2) NULL,
    [YOS15]            NUMERIC (6, 2) NULL,
    [YOS16]            NUMERIC (6, 2) NULL,
    [YOS17]            NUMERIC (6, 2) NULL,
    [YOS18]            NUMERIC (6, 2) NULL,
    [YOS19]            NUMERIC (6, 2) NULL,
    [YOS20]            NUMERIC (6, 2) NULL,
    [YOS21]            NUMERIC (6, 2) NULL,
    [YOS22]            NUMERIC (6, 2) NULL,
    [YOS23]            NUMERIC (6, 2) NULL,
    [YOS24]            NUMERIC (6, 2) NULL,
    [YOS25]            NUMERIC (6, 2) NULL,
    [YOS26]            NUMERIC (6, 2) NULL,
    [YOS27]            NUMERIC (6, 2) NULL,
    [YOS28]            NUMERIC (6, 2) NULL,
    [YOS29]            NUMERIC (6, 2) NULL,
    [YOS30]            NUMERIC (6, 2) NULL,
    [YOS31]            NUMERIC (6, 2) NULL,
    [YOS32]            NUMERIC (6, 2) NULL,
    [YOS33]            NUMERIC (6, 2) NULL,
    [YOS34]            NUMERIC (6, 2) NULL,
    [YOS35]            NUMERIC (6, 2) NULL,
    [YOS36]            NUMERIC (6, 2) NULL,
    [YOS37]            NUMERIC (6, 2) NULL,
    [YOS38]            NUMERIC (6, 2) NULL,
    [YOS39]            NUMERIC (6, 2) NULL,
    [YOS40]            NUMERIC (6, 2) NULL,
    [YOSGreaterThan40] NUMERIC (6, 2) NULL,
    [YOSUnknown]       NUMERIC (6, 2) NULL,
    [YOSTotal]         NUMERIC (6, 2) NULL,
    CONSTRAINT [PK_ContinuationRates_Promoted] PRIMARY KEY CLUSTERED ([PayPlan] ASC, [CMF] ASC, [GradeType] ASC, [GradeLevel] ASC, [AccessionQuality] ASC)
);

