CREATE TABLE [DMDC].[ETS_Population] (
    [PayPlan]           NVARCHAR (3) NOT NULL,
    [CMF]               NVARCHAR (3) NOT NULL,
    [GradeLevel]        TINYINT      NOT NULL,
    [AccessionQuality]  TINYINT      NOT NULL,
    [METS]              NVARCHAR (3) NOT NULL,
    [YOS_0]             NUMERIC (7)  NULL,
    [YOS_1]             NUMERIC (7)  NULL,
    [YOS_2]             NUMERIC (7)  NULL,
    [YOS_3]             NUMERIC (7)  NULL,
    [YOS_4]             NUMERIC (7)  NULL,
    [YOS_5]             NUMERIC (7)  NULL,
    [YOS_6]             NUMERIC (7)  NULL,
    [YOS_7]             NUMERIC (7)  NULL,
    [YOS_8]             NUMERIC (7)  NULL,
    [YOS_9]             NUMERIC (7)  NULL,
    [YOS_10]            NUMERIC (7)  NULL,
    [YOS_11]            NUMERIC (7)  NULL,
    [YOS_12]            NUMERIC (7)  NULL,
    [YOS_13]            NUMERIC (7)  NULL,
    [YOS_14]            NUMERIC (7)  NULL,
    [YOS_15]            NUMERIC (7)  NULL,
    [YOS_16]            NUMERIC (7)  NULL,
    [YOS_17]            NUMERIC (7)  NULL,
    [YOS_18]            NUMERIC (7)  NULL,
    [YOS_19]            NUMERIC (7)  NULL,
    [YOS_20]            NUMERIC (7)  NULL,
    [YOS_21]            NUMERIC (7)  NULL,
    [YOS_22]            NUMERIC (7)  NULL,
    [YOS_23]            NUMERIC (7)  NULL,
    [YOS_24]            NUMERIC (7)  NULL,
    [YOS_25]            NUMERIC (7)  NULL,
    [YOS_26]            NUMERIC (7)  NULL,
    [YOS_27]            NUMERIC (7)  NULL,
    [YOS_28]            NUMERIC (7)  NULL,
    [YOS_29]            NUMERIC (7)  NULL,
    [YOS_30]            NUMERIC (7)  NULL,
    [YOS_31]            NUMERIC (7)  NULL,
    [YOS_32]            NUMERIC (7)  NULL,
    [YOS_33]            NUMERIC (7)  NULL,
    [YOS_34]            NUMERIC (7)  NULL,
    [YOS_35]            NUMERIC (7)  NULL,
    [YOS_36]            NUMERIC (7)  NULL,
    [YOS_37]            NUMERIC (7)  NULL,
    [YOS_38]            NUMERIC (7)  NULL,
    [YOS_39]            NUMERIC (7)  NULL,
    [YOS_40]            NUMERIC (7)  NULL,
    [YOS_GreaterThan40] NUMERIC (7)  NULL,
    [YOS_Unknown]       NUMERIC (7)  NULL,
    [YOS_Total]         NUMERIC (7)  NULL,
    CONSTRAINT [PK_ETS_Population] PRIMARY KEY CLUSTERED ([PayPlan] ASC, [CMF] ASC, [GradeLevel] ASC, [AccessionQuality] ASC, [METS] ASC)
);

