
/****** Script for SelectTopNRows command from SSMS  ******/
create view [analysis].[PythonPositionCostElement] as 
SELECT [PayPlan]
      ,[CategoryGroupCode]
      ,[CategoryGroupDescription]
      ,[CategorySubgroupCode]
      ,[CategorySubgroupDescription]
      ,[CareerProgramNumber]
      ,[CP_title]
      ,[Strl]
      ,[LocationId]
      ,[Location_name]
      ,[DependentStatus]
      ,[NumberOfDependents]
      ,[CostElementId]
      --,[AppropriationGroup]
      --,[APPN]
      ,[CostElementCategory]
      ,[CostElementName]
      --,[Description]
      --,[ArmyCesTitle]
      --,[OsdCapeCesTitle]
      --,[showOrder]
      --,[GradeType]
      ,[GradeLevel]
      ,[WeaponSystemName]
      ,[WeaponSystemId]
      , Amount
      ,[AmcosVersionId]
  FROM [data].[CostsWithDescriptions]