CREATE TABLE [PaySchedule].[OpmIGRaw](
	[PayPlan] [NVARCHAR](3) NOT NULL,
	[Level] [NVARCHAR](15) NOT NULL,
	[DateEffective] [DATE] NOT NULL,
	[RateType] [NVARCHAR](25) NOT NULL,
	[Rate] [NUMERIC](10, 2) NULL,
	[AmcosVersionId] [INT] NOT NULL,
 CONSTRAINT [PK_PaySchedule_IG_Series_raw] PRIMARY KEY CLUSTERED 
(
	[PayPlan] ASC,
	[Level] ASC,
	[RateType] ASC,
	[AmcosVersionId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO