'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ProjectReport

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ibDownloadExcel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibDownloadExcel As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''hidDownload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidDownload As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''dvProjectDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvProjectDetails As Global.System.Web.UI.WebControls.DetailsView

    '''<summary>
    '''odsRepProjectDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsRepProjectDetails As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''gvProjectReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvProjectReport As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''SqlDataReportSelection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataReportSelection As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''InflationGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InflationGridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblYearForTheDiscount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblYearForTheDiscount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvDiscountRates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvDiscountRates As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gvProjectInventory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvProjectInventory As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''litNoteSpecialPay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litNoteSpecialPay As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lblUndiscounted_Default control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUndiscounted_Default As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvUndiscounted_Default control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvUndiscounted_Default As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''cceSalaryOverLimitNoteUndiscounted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cceSalaryOverLimitNoteUndiscounted As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblDiscounted_Default control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDiscounted_Default As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvDiscounted_Default control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvDiscounted_Default As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''cceSalaryOverLimitNoteDiscounted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cceSalaryOverLimitNoteDiscounted As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
