'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AdminApproval
    
    '''<summary>
    '''UserList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserList As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''EmailSentPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmailSentPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''EmailFrom1Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmailFrom1Literal As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''EmailTo1Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmailTo1Literal As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''EmailSubject1Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmailSubject1Literal As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''EmailBody1Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmailBody1Literal As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''EmailFrom2Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmailFrom2Literal As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''EmailTo2Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmailTo2Literal As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''EmailSubject2Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmailSubject2Literal As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''EmailBody2Literal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmailBody2Literal As Global.System.Web.UI.WebControls.Literal
End Class
