'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AdminLog
    
    '''<summary>
    '''LogEntryDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LogEntryDetails As Global.System.Web.UI.WebControls.DetailsView
    
    '''<summary>
    '''EventLogDetailsDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EventLogDetailsDataSource As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''EventLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EventLog As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''EventLogDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EventLogDataSource As Global.System.Web.UI.WebControls.SqlDataSource
End Class
