'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UserList
    
    '''<summary>
    '''hidDownload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidDownload As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lblFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFirstName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbFirstName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbLastName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbLastName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblArmyRank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblArmyRank As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbArmyRank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbArmyRank As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblMacom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMacom As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''macomList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents macomList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblOfficeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOfficeName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbOfficeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbOfficeName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblCompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCompanyName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbCompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCompanyName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblDateCreatedFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateCreatedFrom As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtDateCreatedFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateCreatedFrom As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDateCreatedTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateCreatedTo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cvCreatedFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvCreatedFrom As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''calendarDateCreatedFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calendarDateCreatedFrom As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''cvCreatedTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvCreatedTo As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''calendarDateCreatedTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calendarDateCreatedTo As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''lblDateUpdatedFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateUpdatedFrom As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtDateUpdatedFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateUpdatedFrom As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDateUpdatedTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateUpdatedTo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cvUpdatedFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvUpdatedFrom As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''calendarDateUpdatedFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calendarDateUpdatedFrom As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''cvUpdatedTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvUpdatedTo As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''calendarDateUPdatedTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calendarDateUPdatedTo As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''lblLastLoginFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastLoginFrom As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtLastLoginFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastLoginFrom As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLastLoginTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastLoginTo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cvLastLoginFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvLastLoginFrom As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''calendarLastLoginFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calendarLastLoginFrom As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''cvLastLoginTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvLastLoginTo As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''calendarLastLoginTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calendarLastLoginTo As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''lblLoginFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLoginFrom As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtLoginFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLoginFrom As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLoginTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLoginTo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cvLoginFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvLoginFrom As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''calendarLoginFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calendarLoginFrom As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''cvLoginTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvLoginTo As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''calendarLoginTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calendarLoginTo As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''lblLastApprovedFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastApprovedFrom As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtLastApprovedFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastApprovedFrom As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLastApprovedTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastApprovedTo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cvLastApprovedFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvLastApprovedFrom As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''calendarLastApprovedFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calendarLastApprovedFrom As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''cvLastApprovedTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvLastApprovedTo As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''calendarLastApprovedTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calendarLastApprovedTo As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''lblLastDeniedFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastDeniedFrom As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtLastDeniedFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastDeniedFrom As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLastDeniedTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastDeniedTo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cvLastDeniedFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvLastDeniedFrom As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''calendarLastDeniedFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calendarLastDeniedFrom As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''cvLastDeniedTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvLastDeniedTo As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''calendarLastDeniedTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calendarLastDeniedTo As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblRecCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRecCount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ibDownloadExcel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibDownloadExcel As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''GridView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView1 As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''tbFirstNameEx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbFirstNameEx As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbLastNameEx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbLastNameEx As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbArmyRankEx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbArmyRankEx As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbMacomEx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbMacomEx As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbOfficeNameEx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbOfficeNameEx As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbCompanyNameEx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCompanyNameEx As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbDateCreatedFromEx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDateCreatedFromEx As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbDateCreatedToEx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDateCreatedToEx As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbDateUpdatedFromEx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDateUpdatedFromEx As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbDateUpdatedToEx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbDateUpdatedToEx As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbLastLoginFromEx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbLastLoginFromEx As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbLastLoginToEx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbLastLoginToEx As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbLoginFromEx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbLoginFromEx As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbLoginToEx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbLoginToEx As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''GridView2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView2 As Global.System.Web.UI.WebControls.GridView
End Class
