CREATE TABLE [analysis].[CostsCompare] (
    [PayPlan]               NVARCHAR (3)    NOT NULL,
    [CategoryGroupCode]     NVARCHAR (4)    NOT NULL,
    [CategorySubgroupCode]  NVARCHAR (5)    NOT NULL,
    [CategoryGroupName]     NVARCHAR (150)  NULL,
    [CategorySubgroupName]  NVARCHAR (150)  NULL,
    [GradeLevel]            TINYINT         NOT NULL,
    [cpnum]                 INT             NOT NULL,
    [cpname]                NVARCHAR (250)  NOT NULL,
    [CostElementName]       NVARCHAR (250)  NOT NULL,
    [LocationName]          NVARCHAR (100)  NULL,
    [priorAmount]           FLOAT (53)      NOT NULL,
    [currentAmount]         FLOAT (53)      NOT NULL,
    [priorinventory]        INT             NULL,
    [currentinventory]      INT             NULL,
    [diff]                  NUMERIC (18, 2) NULL,
    [diffperc]              NUMERIC (18, 2) NULL,
    [strl]                  NVARCHAR (200)  NOT NULL,
    [CostElementId]         INT             NOT NULL,
    [AppropriationGroup]    NVARCHAR (50)   NULL,
    [APPN]                  NVARCHAR (25)   NOT NULL,
    [CostElementCategory]   NVARCHAR (50)   NOT NULL,
    [GradeType]             NVARCHAR (3)    NULL,
    [WeaponSystemId]        INT             NULL,
    [weaponsystemname]      NVARCHAR (150)  NULL,
    [locationid]            INT             NOT NULL,
    [locationtype]          NVARCHAR (100)  NOT NULL,
    [prioramcosversionid]   INT             NOT NULL,
    [currentamcosversionid] INT             NOT NULL,
    [DependentStatus]       NVARCHAR (50)   NULL,
    [numberofdependents]    INT             NULL,
    [analysistime]          DATETIME        NOT NULL
);

