CREATE TABLE [analysis].[TempCosts] (
    [RowId]                BIGINT          NOT NULL,
    [PayPlan]              NVARCHAR (3)    NOT NULL,
    [CategoryGroupCode]    NVARCHAR (4)    NOT NULL,
    [CategorySubgroupCode] NVARCHAR (5)    NOT NULL,
    [CareerProgramNumber]  NVARCHAR (2)    NOT NULL,
    [LocationId]           INT             NOT NULL,
    [Strl]                 NVARCHAR (20)   NOT NULL,
    [CostElementId]        INT             NOT NULL,
    [WeaponSystemId]       INT             NOT NULL,
    [GradeType]            NVARCHAR (3)    NOT NULL,
    [GradeLevel]           TINYINT         NOT NULL,
    [DependentStatus]      NVARCHAR (25)   NOT NULL,
    [NumberOfDependents]   INT             NOT NULL,
    [Amount]               FLOAT (53)      NOT NULL,
    [CrunchTime]           SMALLDATETIME   NULL,
    [AmcosVersionId]       INT             NOT NULL,
    [AppropriationGroup]   NVARCHAR (50)   NULL,
    [APPN]                 NVARCHAR (25)   NOT NULL,
    [CostElementCategory]  NVARCHAR (50)   NOT NULL,
    [CostElementName]      NVARCHAR (250)  NOT NULL,
    [Description]          NVARCHAR (3000) NULL,
    [ArmyCesTitle]         NVARCHAR (250)  NULL,
    [OsdCapeCesTitle]      NVARCHAR (250)  NULL,
    [Amort]                INT             NULL,
    [Model]                INT             NULL,
    [Locality]             BIT             NULL,
    [ApplyInflation]       BIT             NULL,
    [IsLocationSpecific]   BIT             NOT NULL,
    [showOrder]            INT             NULL
);

