CREATE TABLE [crunch].[TempATRRS_ATRM_Crs_MOS] (
    [ATRRS_Num_students]   FLOAT (53)     NULL,
    [ATRRS_CrsType]        NVARCHAR (255) NULL,
    [ATRRS_Branch]         NVARCHAR (255) NULL,
    [ATRRS_MOS]            NVARCHAR (255) NULL,
    [ATRRS_GradeLevel]     NVARCHAR (255) NULL,
    [ATRRS_Crs_Title]      NVARCHAR (255) NULL,
    [ATRRS_School]         NVARCHAR (255) NULL,
    [ATRRS_Component]      NVARCHAR (255) NULL,
    [ATRRS_Crs_Num]        NVARCHAR (255) NULL,
    [ATRRS_Sch_Code]       NVARCHAR (255) NULL,
    [ATRRS_Version_id]     INT            NULL,
    [AmcosVersionId]       INT            NULL,
    [ATRRS_Key]            NVARCHAR (255) NULL,
    [ATRM_Key]             NVARCHAR (255) NULL,
    [ATRM_Version_id]      INT            NULL,
    [ATRM_Sch_Code]        NVARCHAR (255) NULL,
    [ATRM_Crs_Num]         NVARCHAR (255) NULL,
    [ATRM_Crs_Title]       NVARCHAR (255) NULL,
    [ATRM_Location]        NVARCHAR (255) NULL,
    [ATRM_Activity]        NVARCHAR (255) NULL,
    [ATRM_Length_wks]      FLOAT (53)     NULL,
    [ATRM_EGRADS]          FLOAT (53)     NULL,
    [ATRM_Modal_Grade]     NVARCHAR (255) NULL,
    [ATRM_Frequency]       FLOAT (53)     NULL,
    [ATRM_Flying_Hrs]      FLOAT (53)     NULL,
    [ATRM_TMW_EGRD]        FLOAT (53)     NULL,
    [ATRM_MPA]             FLOAT (53)     NULL,
    [ATRM_OMA]             FLOAT (53)     NULL,
    [ATRM_Other]           FLOAT (53)     NULL,
    [Exception]            NVARCHAR (50)  NULL,
    [Crs_Type_O]           NVARCHAR (4)   NULL,
    [Crs_Type_E]           NVARCHAR (4)   NULL,
    [WeaponSystemName]     NVARCHAR (50)  NULL,
    [AOC]                  NVARCHAR (8)   NULL,
    [WOMOS]                NVARCHAR (8)   NULL,
    [MOS]                  NVARCHAR (8)   NULL,
    [O_GradeLevel_Floor]   INT            NULL,
    [O_GradeLevel_Ceiling] INT            NULL,
    [W_GradeLevel_Floor]   INT            NULL,
    [W_GradeLevel_Ceiling] INT            NULL,
    [E_GradeLevel_Floor]   INT            NULL,
    [E_GradeLevel_Ceiling] INT            NULL,
    [final_crs_type]       NVARCHAR (10)  NULL,
    [final_MOS]            NVARCHAR (10)  NULL,
    [final_Branch]         NVARCHAR (10)  NULL,
    [final_Grade]          NVARCHAR (10)  NULL,
    [final_GradeType]      NVARCHAR (10)  NULL,
    [final_GradeLevel]     NVARCHAR (10)  NULL,
    [payplan]              NVARCHAR (10)  NULL,
    [atrrs_tot_students]   INT            NULL,
    [adj_students]         FLOAT (53)     NULL,
    [running_adj_students] FLOAT (53)     NULL,
    [inventory]            INT            NULL,
    [inv_add]              FLOAT (53)     NULL,
    [total_inv_add]        FLOAT (53)     NULL,
    [final_adj_inv]        FLOAT (53)     NULL,
    [final_adj_students]   FLOAT (53)     NULL
);

