CREATE TABLE [crunch].[TempATRRS_ATRM_Raw] (
    [Exception]          NVARCHAR (50)  NULL,
    [ATRM_Other]         FLOAT (53)     NULL,
    [ATRM_OMA]           FLOAT (53)     NULL,
    [ATRM_MPA]           FLOAT (53)     NULL,
    [ATRM_TMW_EGRD]      FLOAT (53)     NULL,
    [ATRM_Flying_Hrs]    FLOAT (53)     NULL,
    [ATRM_Frequency]     FLOAT (53)     NULL,
    [ATRM_Modal_Grade]   NVARCHAR (255) NULL,
    [ATRM_EGRADS]        FLOAT (53)     NULL,
    [ATRM_Length_wks]    FLOAT (53)     NULL,
    [ATRM_Activity]      NVARCHAR (255) NULL,
    [ATRM_Location]      NVARCHAR (255) NULL,
    [ATRM_Crs_Title]     NVARCHAR (255) NULL,
    [ATRM_Crs_Num]       NVARCHAR (255) NULL,
    [ATRM_Sch_Code]      NVARCHAR (255) NULL,
    [ATRM_Version_id]    INT            NULL,
    [ATRM_Key]           NVARCHAR (255) NULL,
    [ATRRS_Key]          NVARCHAR (255) NULL,
    [AmcosVersionId]     INT            NULL,
    [ATRRS_Version_id]   INT            NULL,
    [ATRRS_Sch_Code]     NVARCHAR (255) NULL,
    [ATRRS_Crs_Num]      NVARCHAR (255) NULL,
    [ATRRS_Component]    NVARCHAR (255) NULL,
    [ATRRS_School]       NVARCHAR (255) NULL,
    [ATRRS_Crs_Title]    NVARCHAR (255) NULL,
    [ATRRS_GradeLevel]   NVARCHAR (255) NULL,
    [ATRRS_MOS]          NVARCHAR (255) NULL,
    [ATRRS_Branch]       NVARCHAR (255) NULL,
    [ATRRS_CrsType]      NVARCHAR (255) NULL,
    [ATRRS_Num_students] FLOAT (53)     NULL
);

