CREATE TABLE [crunch].[TempTraining_Costs] (
    [WeaponSystemName]     NVARCHAR (50) NULL,
    [coursetype]           NVARCHAR (10) NULL,
    [PayPlan]              NVARCHAR (3)  NOT NULL,
    [CategoryGroupCode]    NVARCHAR (4)  NOT NULL,
    [CategorySubGroupCode] NVARCHAR (4)  NOT NULL,
    [GradeType]            NVARCHAR (3)  NOT NULL,
    [GradeLevel]           TINYINT       NOT NULL,
    [inventory]            INT           NULL,
    [MPA_MOS]              FLOAT (53)    NULL,
    [OMA_MOS]              FLOAT (53)    NULL,
    [Other_MOS]            FLOAT (53)    NULL,
    [MPA_CMF]              FLOAT (53)    NULL,
    [OMA_CMF]              FLOAT (53)    NULL,
    [Other_CMF]            FLOAT (53)    NULL,
    [MPA_PP]               FLOAT (53)    NULL,
    [OMA_PP]               FLOAT (53)    NULL,
    [other_PP]             FLOAT (53)    NULL,
    [CGLA_MOS_inv]         FLOAT (53)    NULL,
    [CGLA_CMF_Inv]         FLOAT (53)    NULL,
    [CGLA_PP_inv]          FLOAT (53)    NULL,
    [CGLA_MPA]             FLOAT (53)    NULL,
    [CGLA_OMA]             FLOAT (53)    NULL,
    [CGLA_Other]           FLOAT (53)    NULL,
    [RPA_NGPA]             FLOAT (53)    NULL,
    [OMAR_OMNG]            FLOAT (53)    NULL,
    [WeaponSystemId]       INT           NULL
);

