-- PostgreSQL schema bootstrap for AMCOS

CREATE EXTENSION IF NOT EXISTS postgis;

CREATE SCHEMA IF NOT EXISTS lookup;
CREATE SCHEMA IF NOT EXISTS data;
CREATE SCHEMA IF NOT EXISTS webuser;
CREATE SCHEMA IF NOT EXISTS web;
CREATE SCHEMA IF NOT EXISTS warehouse;
CREATE SCHEMA IF NOT EXISTS crunch;
CREATE SCHEMA IF NOT EXISTS analysis;
CREATE SCHEMA IF NOT EXISTS "BLS_OES";
CREATE SCHEMA IF NOT EXISTS "BLS_ECT";
CREATE SCHEMA IF NOT EXISTS "DMDC";
CREATE SCHEMA IF NOT EXISTS "POS";
CREATE SCHEMA IF NOT EXISTS "PaySchedule";
CREATE SCHEMA IF NOT EXISTS "load_GFEBS";
CREATE SCHEMA IF NOT EXISTS load_inventory;
CREATE SCHEMA IF NOT EXISTS load_training;
CREATE SCHEMA IF NOT EXISTS quicksight;
CREATE SCHEMA IF NOT EXISTS test;
CREATE SCHEMA IF NOT EXISTS xwalk;
CREATE SCHEMA IF NOT EXISTS dataload;
