-- Converted data schema tables from AMCOS SQL Server project

-- Source: AMCOS.AMCOS2020_MAR/data/Tables/AsafmcJointInflationRates.sql
CREATE TABLE data.asafmcjointinflationrates (
    conversiontype varchar(25) NOT NULL,
    baseyear varchar(4) NOT NULL,
    targetyear varchar(4) NOT NULL,
    appropriation varchar(25) NOT NULL,
    amount numeric(18, 15) NOT NULL,
    amcosversionid integer NOT NULL,
    CONSTRAINT pk_asafmcjointinflationrates PRIMARY KEY (conversiontype , baseyear , targetyear , appropriation , amcosversionid )
);

-- Source: AMCOS.AMCOS2020_MAR/data/Tables/AvalaraStateTax.sql
CREATE TABLE data.avalarastatetax (
    state varchar(2) NOT NULL,
    zipcode varchar(5) NOT NULL,
    taxregionname varchar(255) NOT NULL,
    staterate numeric(8, 6) NOT NULL,
    estimatedcombinedrate numeric(8, 6) NOT NULL,
    estimatedcountyrate numeric(8, 6) NOT NULL,
    estimatedcityrate numeric(8, 6) NOT NULL,
    estimatedspecialrate numeric(8, 6) NOT NULL,
    risklevel integer NOT NULL,
    amcosversionidstart integer NOT NULL,
    amcosversionidend integer NOT NULL,
    CONSTRAINT pk_avalarastatetax PRIMARY KEY ( state , zipcode , amcosversionidend )
);
ALTER TABLE data.avalarastatetax ALTER COLUMN amcosversionidstart SET DEFAULT 1;
ALTER TABLE data.avalarastatetax ALTER COLUMN amcosversionidend SET DEFAULT 999999;

-- Source: AMCOS.AMCOS2020_MAR/data/Tables/FmsWebLockpointTdochdr.sql
CREATE TABLE data.fmsweblockpointtdochdr (
    ccnum_macom varchar(2) NULL,
    docno varchar(10) NOT NULL,
    ccnum_chgnr_fy varchar(4) NOT NULL,
    docst varchar(1) NULL,
    anlcd varchar(32) NULL,
    arind varchar(1) NULL,
    bccno varchar(6) NULL,
    bdocn varchar(10) NULL,
    class varchar(1) NULL,
    cuasc varchar(4) NULL,
    dedte timestamp NULL,
    docow varchar(1) NULL,
    docsd timestamp NULL,
    eflag varchar(1) NULL,
    laact varchar(6) NULL,
    lname_tdh varchar(55) NULL,
    lvldown timestamp NULL,
    lvlup timestamp NULL,
    ppaco varchar(2) NULL,
    prtcd varchar(1) NULL,
    repco_tdh varchar(1) NULL,
    dp99 varchar(6) NULL,
    sdocn varchar(10) NULL,
    shadow varchar(1) NULL,
    shpcd varchar(1) NULL,
    shpdt timestamp NULL,
    sitecd varchar(4) NULL,
    stccno varchar(6) NULL,
    strpr timestamp NULL,
    tpaco varchar(2) NULL,
    trdte timestamp NULL,
    trfrm varchar(2) NULL,
    uicer varchar(1) NULL,
    uicod varchar(6) NOT NULL,
    amcosversionid integer NOT NULL,
    CONSTRAINT pk_fmsweblockpointtdochdr PRIMARY KEY (docno , ccnum_chgnr_fy , uicod , amcosversionid )
);

-- Source: AMCOS.AMCOS2020_MAR/data/Tables/FmsWebLockpointTperdet.sql
CREATE TABLE data.fmsweblockpointtperdet (
    ccnum_macom varchar(2) NULL,
    docno varchar(10) NOT NULL,
    ccnum_chgnr_fy varchar(4) NOT NULL,
    amsco varchar(8) NOT NULL,
    amser varchar(1) NULL,
    asi01 varchar(2) NULL,
    asi02 varchar(2) NULL,
    asi03 varchar(2) NULL,
    asi04 varchar(2) NULL,
    austr varchar(50) NULL,
    brnch varchar(2) NULL,
    chgst varchar(1) NULL,
    civcc varchar(2) NULL,
    covcd_pd varchar(1) NULL,
    ctype varchar(3) NULL,
    eflag varchar(1) NULL,
    grade varchar(2) NOT NULL,
    ident varchar(1) NULL,
    psn varchar(8) NULL,
    licco varchar(2) NULL,
    lnsts varchar(1) NULL,
    lpind varchar(4) NULL,
    mdepk varchar(4) NULL,
    mdper varchar(1) NULL,
    micat varchar(1) NULL,
    parno varchar(4) NOT NULL,
    pepost varchar(6) NULL,
    perln varchar(3) NOT NULL,
    posco varchar(6) NOT NULL,
    ppsrq varchar(1) NULL,
    ppsst varchar(1) NULL,
    prmk1 varchar(2) NULL,
    prmk2 varchar(2) NULL,
    prmk3 varchar(2) NULL,
    prmk4 varchar(2) NULL,
    psirq varchar(1) NULL,
    psntl varchar(22) NULL,
    rqstr varchar(50) NULL,
    sqi2d varchar(1) NULL,
    cmu varchar(3) NULL,
    supv varchar(1) NULL,
    tduic varchar(2) NULL,
    ccp varchar(2) NULL,
    cafc varchar(4) NULL,
    fsc varchar(4) NULL,
    mmc varchar(1) NULL,
    amcosversionid integer NOT NULL,
    CONSTRAINT pk_fmsweblockpointtperdet PRIMARY KEY (docno , ccnum_chgnr_fy , amsco , grade , parno , perln , posco , amcosversionid )
);

-- Source: AMCOS.AMCOS2020_MAR/data/Tables/FmsWebSacsHeader.sql
CREATE TABLE data.fmswebsacsheader (
    runid integer NOT NULL,
    uic varchar(6) NOT NULL,
    edatei integer NOT NULL,
    tpsn varchar(5) NULL,
    macom varchar(2) NULL,
    actco varchar(1) NULL,
    adcco varchar(6) NULL,
    mdep varchar(4) NULL,
    compo varchar(1) NULL,
    untds varchar(21) NULL,
    carss varchar(2) NULL,
    typco varchar(1) NULL,
    unmbr varchar(4) NULL,
    fpa varchar(1) NULL,
    dampl varchar(5) NULL,
    src varchar(9) NULL,
    alo varchar(1) NULL,
    srcpara varchar(2) NULL,
    asgmt varchar(2) NULL,
    locco varchar(3) NULL,
    amsco varchar(8) NULL,
    brnch varchar(2) NULL,
    ccnum varchar(6) NULL,
    docno varchar(11) NULL,
    dpmnt varchar(4) NULL,
    elseq varchar(2) NULL,
    forco varchar(1) NULL,
    mbcmd varchar(2) NULL,
    mbloc varchar(3) NULL,
    mbprd varchar(3) NULL,
    mbsta varchar(9) NULL,
    mtoec varchar(6) NULL,
    ntref varchar(2) NULL,
    phase varchar(1) NULL,
    robco varchar(4) NULL,
    roc varchar(3) NULL,
    staco varchar(5) NULL,
    tdate integer NULL,
    ulccc varchar(3) NULL,
    utc varchar(5) NULL,
    CONSTRAINT pk_fmswebsacsheader PRIMARY KEY (runid , uic , edatei )
);

-- Source: AMCOS.AMCOS2020_MAR/data/Tables/FmsWebSacsPersonnel.sql
CREATE TABLE data.fmswebsacspersonnel (
    id integer GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    runid integer NULL,
    uic varchar(6) NULL,
    edatei integer NULL,
    rqboi integer NULL,
    auboi integer NULL,
    sorce integer NULL,
    mduic varchar(2) NULL,
    grade varchar(3) NULL,
    mos varchar(5) NULL,
    rmks1 varchar(2) NULL,
    rmks2 varchar(2) NULL,
    rmks3 varchar(2) NULL,
    rmks4 varchar(2) NULL,
    amsco varchar(8) NULL,
    lic varchar(2) NULL,
    asi01 varchar(2) NULL,
    asi02 varchar(2) NULL,
    asi03 varchar(2) NULL,
    asi04 varchar(2) NULL,
    sqi2d varchar(1) NULL,
    psntl varchar(22) NULL,
    branch varchar(2) NULL,
    ident varchar(1) NULL,
    pers_cat varchar(1) NULL,
    rqstr integer NULL,
    austr integer NULL,
    cmf varchar(2) NULL,
    CONSTRAINT pk_fmswebsacspersonnel PRIMARY KEY (id )
);

