CREATE TABLE [webuser].[AMCOSUser] (
    [UserId]           NVARCHAR (50)  NOT NULL,
    [FirstName]        NVARCHAR (50)  NOT NULL,
    [MiddleName]       NVARCHAR (50)  NULL,
    [LastName]         NVARCHAR (50)  NOT NULL,
    [Email]            NVARCHAR (50)  NOT NULL,
    [Prefix]           NVARCHAR (5)   NULL,
    [AkoId]            NVARCHAR (50)  NULL,
    [DodId]            NVARCHAR (50)  NULL,
    [ComPhone]         NVARCHAR (50)  NULL,
    [Dsn]              NVARCHAR (50)  NULL,
    [InternationalNo]  NVARCHAR (30)  NULL,
    [ArmyAccountType]  NVARCHAR (50)  NULL,
    [ArmyRank]         NVARCHAR (50)  NULL,
    [OfficeName]       NVARCHAR (100) NULL,
    [CompanyName]      NVARCHAR (100) NULL,
    [Macom]            NVARCHAR (50)  NULL,
    [AccessStatus]     SMALLINT       NULL,
    [UserStatus]       NVARCHAR (14)  NULL,
    [UserRole]         NVARCHAR (50)  NULL,
    [SelfAccountType]  NVARCHAR (10)  NULL,
    [SponsorUserId]    NVARCHAR (50)  NULL,
    [LastLogin]        DATETIME       NULL,
    [DateCreated]      DATETIME       NOT NULL,
    [LastUpdate]       DATETIME       NOT NULL,
    [LastApprovedDate] DATETIME       NULL,
    [LastDeniedDate]   DATETIME       NULL,
    CONSTRAINT [PK_AMCOSUser] PRIMARY KEY CLUSTERED ([UserId] ASC)
);

