'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class LiteDefault
    
    '''<summary>
    '''selectedPayPlan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selectedPayPlan As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''selectedPayPlanText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selectedPayPlanText As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''selectedCostSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selectedCostSummary As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''selectedCategoryGroupCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selectedCategoryGroupCode As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''selectedCategorySubgroupCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selectedCategorySubgroupCode As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''selectedCareerProgramNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selectedCareerProgramNumber As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''selectedLocationId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selectedLocationId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''selectedLocationText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selectedLocationText As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''selectedScienceTechnologyReinventionLaboratory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selectedScienceTechnologyReinventionLaboratory As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''selectedDependentStatusText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selectedDependentStatusText As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''selectedNumberOfDependents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selectedNumberOfDependents As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''inputOverheadPercent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputOverheadPercent As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''selectedInflationConversionType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selectedInflationConversionType As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''selectedInflationYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selectedInflationYear As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hidUserId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidUserId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''exportButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents exportButton As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ibDownloadExcel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibDownloadExcel As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''showCostsButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents showCostsButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''AppropriationGroupSummaryUpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AppropriationGroupSummaryUpdatePanel As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''AppropriationGroupGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AppropriationGroupGridView As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''InflationRatesHeaderLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InflationRatesHeaderLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''InflationRatesUpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InflationRatesUpdatePanel As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''InflationRatesGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InflationRatesGridView As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''lblPayTableTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPayTableTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CostsUpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CostsUpdatePanel As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''CostsGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CostsGridView As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''liHighlightNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liHighlightNote As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
